# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'WatchPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.7.1'
  pod 'RxCocoa', '6.7.1'
  pod 'RxGesture'

  # Pods for WatchPlayer

  target 'WatchPlayerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.7.1'
    pod 'RxTest', '6.7.1'
  end

  target 'WatchPlayerUITests' do
    # Pods for testing
    pod 'RxBlocking', '6.7.1'
    pod 'RxTest', '6.7.1'
  end

end
